---
datacenter:
  children:
    routers:
      hosts:
        192.168.39.2[0:3]:
      vars:
        testVar: 999
    switches:
      hosts:
        192.168.39.20:
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_user: spacelabs
    ansible_ssh_pass: Spacelabs-fse3051
    ansible_become_password: Spacelabs-fse3051
    ntp_servers:
      - 128.138.140.44

